CREATE DATABASE  HouseholdInventoryDb;

USE HouseholdInventoryDb;

CREATE TABLE Categories (
	Id INT IDENTITY PRIMARY KEY,
	Cat_Name NVARCHAR(100) NOT NULL,
	Cat_Description NVARCHAR(255) NULL

);

CREATE TABLE Brands (
	Id INT IDENTITY PRIMARY KEY,
	Br_Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Stores (
	Id INT IDENTITY PRIMARY KEY,
	St_Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Items (
	Id INT IDENTITY PRIMARY KEY,
	It_Name NVARCHAR(150) NOT NULL,
	Category_Id INT NOT NULL FOREIGN KEY REFERENCES Categories(Id),
	Threshold DECIMAL(10,2) NOT NULL DEFAULT 0,
	CreatedAt DATETIME NOT NULL DEFAULT GETUTCDATE()
);

CREATE TABLE ItemBrands (
	ItemId INT NOT NULL FOREIGN KEY REFERENCES Items(Id),
	BrandId INT NOT NULL FOREIGN KEY REFERENCES Brands(Id),
	Flag NVARCHAR(20) NOT NULL DEFAULT 'NEUTRAL',
	Reason NVARCHAR(255) NULL,
	PRIMARY KEY (ItemId, BrandId)
);

CREATE TABLE Transactions (
	Id INT IDENTITY PRIMARY KEY,
	Type NVARCHAR(20) NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT GETUTCDATE(),
	Notes NVARCHAR(255) NULL,
	StoreId INT NULL FOREIGN KEY REFERENCES Stores(Id)
);

CREATE TABLE TransactionLines (
	Id INT IDENTITY PRIMARY KEY,
	TransactionId INT NOT NULL FOREIGN KEY REFERENCES Transactions(Id),
	ItemId INT NOT NULL FOREIGN KEY REFERENCES Items(Id),
	BrandId INT NULL FOREIGN KEY REFERENCES Brands(Id),
	Quantity DECIMAL(10,2) NOT NULL,
	UnitPrice DECIMAL(10,2) NULL,

	CONSTRAINT UQ_TransactionLines_TransactionItemBrand UNIQUE (TransactionId, ItemId, BrandId)
);